version: "3"

services:
  app:
    build: .
    restart: always
    environment:
      POSTGRES_DB: homework2
      POSTGRES_PASSWORD: 123
    links:
      - postgres
    depends_on:
      - postgres
    ports: 
      - "5000:5000"
    volumes:
      - .:/code
    container_name: homework2

  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_DB: homework2
      POSTGRES_PASSWORD: 123
    volumes:
      - .postgres-data:/var/lib/postgresql/data
    container_name: postgres_container